data_path = "{workdir}/echelle_spectra/data"    # path to directory containing .sif files (see output_path for string format)
debug = false                                   # if true, additional print statements are printed
diag_name = "spec_div1"                         # default name of the diagnostic
output_path = "{workdir}/echelle_spectra/out"   # absolute path or string with format "{target}/..." where target is "homedir" or "workdir"